### ISSUE TITLE
feat: also take in account the description of the PR

### ISSUE THREAD

**Issue by nadavsinai-philips** [kevintyj/prlint#11]
### Is there an existing request for this?

- [X] I have searched the existing feature requests

### Is the feature request related to a problem?

yes, prlint will only get the title of the PR

### Describe the solution you'd like

I[ implemented the fix in my fork. ](https://github.com/kevintyj/prlint/commit/88d6ac1128962932683c9da5c78d97a2e2283e5c)so would like to discuss if you'd want a PR.

### What is the definition of done?

PR is being linted with both title and description being taken in to account, not a breaking change to API

### Are you able to assist to bring the feature to reality?

Yes, I can

### Anything else?

In my fork, I also removed the ESM translation feature, I have some js, and some JSON configs and this would not work well with the way you implemented the translation so removed this complexity, I think this is no longer relvant anymore, people can just use .mjs for module syntax

**Comment by kevintyj** [comment]
@nadavsinai-philips Oh wow! this looks really useful! Thanks for the fork and also the work on the source code, I do agree with your comment on ESM conversion, that had to be done because of some of our internal company pipelines. As we move away from our old pipeline and actually committed to full ESM migration, I am thinking of dropping CJS support in the upcoming release. I do not know how many people are actually using this action, but I plan on adding CJS support back in the future with a much more elegant solution than the string replacement thats being done right now. Since v9 of commitment also add pure ESM, this would also be handy as well. I am looking to push updates to this action in the coming weeks as our company changes pipeline! Feel free to raise any additional FR or PRs <3
